In [24]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [25]:
covid=pd.read_csv("coviddatset.csv",squeeze=True)

In [26]:
covid.drop("Wearing Masks",axis=1,inplace=True)
covid.drop("Sanitization from Market",axis=1,inplace=True)

In [27]:
covid.head()

Breathing Problem Fever Dry Cough Sore throat Running Nose Asthma  \
0                No    No        No          No          Yes     No   
1                No    No        No          No          Yes     No   
2                No    No        No          No          Yes     No   
3                No    No        No          No          Yes    Yes   
4                No    No        No          No          Yes     No   

  Chronic Lung Disease Headache Heart Disease Diabetes Hyper Tension Fatigue  \
0                   No      Yes            No       No            No     Yes   
1                  Yes       No            No       No           Yes     Yes   
2                   No      Yes           Yes       No           Yes     Yes   
3                   No      Yes           Yes      Yes            No      No   
4                   No      Yes           Yes      Yes            No     Yes   

  Gastrointestinal Abroad travel Contact with COVID Patient  \
0               No            No                         No   
1               No            No                        Yes   
2               No            No                         No   
3               No            No                         No   
4              Yes            No                         No   

  Attended Large Gathering Visited Public Exposed Places  \
0                      Yes                           Yes   
1                      Yes                           Yes   
2                       No                           Yes   
3                      Yes                            No   
4                       No                            No   

  Family working in Public Exposed Places COVID-19  
0                                     Yes       No  
1                                     Yes       No  
2                                     Yes       No  
3                                      No       No  
4                                     Yes       No

In [28]:
covid.to_csv('coviddataset.csv')

In [29]:
dataset = pd.read_csv('coviddataset.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values
print(X)

[['No' 'No' 'No' ... 'Yes' 'Yes' 'Yes']
 ['No' 'No' 'No' ... 'Yes' 'Yes' 'Yes']
 ['No' 'No' 'No' ... 'No' 'Yes' 'Yes']
 ...
 ['Yes' 'Yes' 'Yes' ... 'Yes' 'No' 'Yes']
 ['Yes' 'Yes' 'Yes' ... 'No' 'Yes' 'Yes']
 ['Yes' 'Yes' 'Yes' ... 'No' 'Yes' 'No']]


In [30]:
df=pd.read_csv("coviddataset.csv",squeeze=True)
df.head()

Unnamed: 0 Breathing Problem Fever Dry Cough Sore throat Running Nose  \
0           0                No    No        No          No          Yes   
1           1                No    No        No          No          Yes   
2           2                No    No        No          No          Yes   
3           3                No    No        No          No          Yes   
4           4                No    No        No          No          Yes   

  Asthma Chronic Lung Disease Headache Heart Disease Diabetes Hyper Tension  \
0     No                   No      Yes            No       No            No   
1     No                  Yes       No            No       No           Yes   
2     No                   No      Yes           Yes       No           Yes   
3    Yes                   No      Yes           Yes      Yes            No   
4     No                   No      Yes           Yes      Yes            No   

  Fatigue Gastrointestinal Abroad travel Contact with COVID Patient  \
0     Yes               No            No                         No   
1     Yes               No            No                        Yes   
2     Yes               No            No                         No   
3      No               No            No                         No   
4     Yes              Yes            No                         No   

  Attended Large Gathering Visited Public Exposed Places  \
0                      Yes                           Yes   
1                      Yes                           Yes   
2                       No                           Yes   
3                      Yes                            No   
4                       No                            No   

  Family working in Public Exposed Places COVID-19  
0                                     Yes       No  
1                                     Yes       No  
2                                     Yes       No  
3                                      No       No  
4                                     Yes       No

In [31]:
df.isnull().sum()

Unnamed: 0                                 0
Breathing Problem                          0
Fever                                      0
Dry Cough                                  0
Sore throat                                0
Running Nose                               0
Asthma                                     0
Chronic Lung Disease                       0
Headache                                   0
Heart Disease                              0
Diabetes                                   0
Hyper Tension                              0
Fatigue                                    0
Gastrointestinal                           0
Abroad travel                              0
Contact with COVID Patient                 0
Attended Large Gathering                   0
Visited Public Exposed Places              0
Family working in Public Exposed Places    0
COVID-19                                   0
dtype: int64

In [33]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 0 0 ... 1 1 1]


In [32]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder()
X = ordinal_encoder.fit_transform(X)
print(X)


[[0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 1. 1.]
 ...
 [1. 1. 1. ... 1. 0. 1.]
 [1. 1. 1. ... 0. 1. 1.]
 [1. 1. 1. ... 0. 1. 0.]]


In [59]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

In [60]:
print(X_test)

[[1. 1. 1. ... 1. 0. 0.]
 [1. 1. 1. ... 1. 0. 1.]
 [1. 1. 1. ... 1. 0. 1.]
 ...
 [1. 1. 1. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [1. 1. 1. ... 0. 1. 1.]]


In [61]:
from sklearn.utils import shuffle
X_train,y_train = shuffle(X_train,y_train, random_state=0)
X_test,y_test = shuffle(X_test,y_test, random_state=0)

In [62]:
print(X_train)

[[1. 1. 1. ... 0. 1. 1.]
 [0. 1. 0. ... 0. 1. 0.]
 [1. 1. 1. ... 1. 1. 0.]
 ...
 [1. 0. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 1. 0. 1.]
 [0. 0. 0. ... 0. 1. 1.]]


In [63]:
print(X_test)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 1. 1.]
 [1. 1. 1. ... 0. 1. 0.]
 ...
 [0. 0. 1. ... 0. 1. 0.]
 [1. 1. 1. ... 0. 1. 1.]
 [0. 0. 0. ... 0. 1. 1.]]


In [64]:
print(y_test)

[0 1 1 1 1 0 1 1 1 0 0 1 1 1 0 1 0 1 0 1 0 1 1 1 1 0 1 1 1 1 0 1 0 1 0 1 0
 1 1 1 0 0 0 1 0 0 0 1 1 0 1 1 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1
 1 1 0 1 0 1 1 0 1 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0
 1 1 0 1 0 1 1 0 1 0 0 1 1 0 1 0 0 1 1 0 0 1 1 1 1 1 1 1 1 1 0 1 0 1 1 0 0
 1 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 0 1 0 0 1 0 0 1 0 0 0 0 1 0
 0 1 0 1 1 1 1 1 0 0 0 0 1 1 1 0 0 0 0 1 1 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0
 0 1 1 0 1 0 1 0 1 0 1 1 1 0 0 0 0 1 1 1 1 1 1 0 1 0 1 0 1 1 1 1 1 0 1 1 1
 1 1 1 0 1 0 0 1 0 0 0 1 1 1 0 0 1 1 1 1 0 0 1 0 0 0 1 1 0 1 0 0 0 1 0 1 0
 0 0 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 0 0 0 1 1 0 0 0 1 0 1 0 1 1 1 0 0 1 0
 1 1 0 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 0 0 0 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 0 0 0 0 1 1 1 0 1 0 1 0 0 1 0 0 0 1 1
 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0 1 0 0 0 0 0 1 1 1 1 1 1 0 1 0 0 0 1 0
 1 0 0 0 0 1 0 0 1 0 0 1 0 0 1 1 1 0 0 1 1 1 1 0 0 0 0 1 0 1 0 1 1 0 1 0 0
 1 0 1 1 0 0 0 1 1 1 0 0 

In [69]:
from xgboost import XGBClassifier
classifier = XGBClassifier(learning_rate=0.1,use_label_encoder=False,n_estimators=1000)
classifier.fit(X_train, y_train)

[17:39:56] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.1, max_delta_step=0,
              max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=1000, n_jobs=8,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', use_label_encoder=False,
              validate_parameters=1, verbosity=None)

In [70]:
from mlxtend.evaluate import bias_variance_decomp
from sklearn import metrics
y_pred = classifier.predict(X_test)
mse, bias, var = bias_variance_decomp(classifier, X_train, y_train, X_test, y_test, loss='0-1_loss', num_rounds=100, random_seed=0)
print('MSE from bias_variance lib [avg expected loss]: %.3f' % mse)
print('Avg Bias: %.3f' % bias)
print('Avg Variance: %.3f' % var)
print('Mean Square error by Sckit-learn lib: %.3f' % metrics.mean_squared_error(y_test,y_pred))

[17:39:57] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[17:39:58] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[17:39:58] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[17:39:59] WARNING: C:/Users/Administrator/workspace/xgboost-win64_rel

In [73]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


[[435   6]
 [  9 392]]


0.982185273159145

In [74]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))


[17:42:19] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[17:42:20] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[17:42:21] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[17:42:21] WARNING: C:/Users/Administrator/workspace/xgboost-win64_rel